baseURL = "/"
languageCode = "en-us"
title = "NCommander's Tech Corner"
theme = "mainroad"
paginate = "10" 
enableGitInfo = true

[permalinks]
  articles = "/articles/:year/:month/:title/"

[menu]
[[menu.main]]
    identifer = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifer = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects"
    weight = 10

[[menu.main]]
    identifer = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = 100

[Author] # Used in authorbox
  name = "Michael Casadevall"
  bio = "Michael has worked in software development for over a decade, and likes to explore and document legacy computer systems that have fallen by the wayside. In addition to computing, he travels, bikes, and reads in his free time. He is currently based in Jersey City, NJ and a member of DEFCON 201."
  avatar = "theme/photo.jpeg"

[Params]
  description = "NCommander's tech write-ups, real life adventures, and more" # Site description. Used in meta description
  copyright = "Michael Casadevall" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true

[Params.style.vars]
  #highlightColor = "#000080" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  #image = "theme/logo.png" # Logo image. Path relative to "static"
  title = "NCommander's Tech Corner" # Logo title, otherwise will use site title
  subtitle = "Investigating the ins and outs of technology" # Logo subtitle

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["ddg-search", "recent", "social", "categories", "languages"]

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "fossfirefighter"
  instagram = "fossfirefighter"
  linkedin = "michael-casadevall-a7622312"
  github = "ncommander"
  email = "michael@casadevell.pro"
  
[[Params.widgets.social.custom]]
  title = "YouTube"
  url = "https://youtube.com/c/NCommander"
  icon = "youtube.svg"
